In [43]:
import numpy as np
import pandas as pd
import tensorflow as tf
from tensorflow import keras
from tensorflow.keras.models import Sequential
from tensorflow.keras import layers

from sklearn.model_selection import train_test_split


In [9]:
# load the dataset

df = pd.read_csv('diabetes.csv', delimiter=',')
df.head()

times_pragnent  glucose_concentration  blood_pressure  skin_thickness  \
0               6                    148              72              35   
1               1                     85              66              29   
2               8                    183              64               0   
3               1                     89              66              23   
4               0                    137              40              35   

   insulin_serum   bmi    dpf  age  class  
0              0  33.6  0.627   50      1  
1              0  26.6  0.351   31      0  
2              0  23.3  0.672   32      1  
3             94  28.1  0.167   21      0  
4            168  43.1  2.288   33      1

In [7]:
df.shape

(768, 9)

In [13]:
# split into input (X) and output (y) variables
X = df.iloc[:,0:8]
y = df.iloc[:,8]


times_pragnent  glucose_concentration  blood_pressure  skin_thickness  \
0                 6                    148              72              35   
1                 1                     85              66              29   
2                 8                    183              64               0   
3                 1                     89              66              23   
4                 0                    137              40              35   
..              ...                    ...             ...             ...   
763              10                    101              76              48   
764               2                    122              70              27   
765               5                    121              72              23   
766               1                    126              60               0   
767               1                     93              70              31   

     insulin_serum   bmi    dpf  age  
0                0  33.6  0.627   50  
1                0  26.6  0.351   31  
2                0  23.3  0.672   32  
3               94  28.1  0.167   21  
4              168  43.1  2.288   33  
..             ...   ...    ...  ...  
763            180  32.9  0.171   63  
764              0  36.8  0.340   27  
765            112  26.2  0.245   30  
766              0  30.1  0.349   47  
767              0  30.4  0.315   23  

[768 rows x 8 columns]

In [27]:
# Define the Tensorflow Model
model = Sequential()

# adding layers

model.add(layers.Dense(12, input_shape=(8,), activation = 'relu'))
model.add(layers.Dense(8, activation='relu'))
model.add(layers.Dense(1, activation='sigmoid'))

In [29]:
model.summary()

Model: "sequential_1"
_________________________________________________________________
 Layer (type)                Output Shape              Param #   
 dense_1 (Dense)             (None, 12)                108       
                                                                 
 dense_2 (Dense)             (None, 8)                 104       
                                                                 
 dense_3 (Dense)             (None, 1)                 9         
                                                                 
Total params: 221 (884.00 Byte)
Trainable params: 221 (884.00 Byte)
Non-trainable params: 0 (0.00 Byte)
_________________________________________________________________


In [37]:
w1,b1 = model.layers[0].get_weights()
w1

array([[-0.07891414, -0.09363458, -0.468769  , -0.3294229 , -0.4888745 ,
        -0.49027178, -0.5453195 , -0.32760316, -0.05880749,  0.5077205 ,
         0.30226964, -0.42945364],
       [ 0.02620167, -0.25415817, -0.08669099,  0.31625473, -0.4570334 ,
         0.14017093, -0.20094776,  0.5259173 , -0.09629399,  0.48114395,
        -0.4466794 , -0.2582326 ],
       [ 0.17173713,  0.5245031 ,  0.5431067 ,  0.11886871,  0.24697113,
         0.24541062,  0.4334706 , -0.19091305, -0.18860191,  0.4148426 ,
        -0.34744197,  0.1204654 ],
       [ 0.46206045, -0.09202248,  0.23470521,  0.50019145,  0.3642667 ,
         0.1675992 , -0.40189725, -0.23405999,  0.3264122 ,  0.35461318,
         0.29219103,  0.29106092],
       [ 0.49818325,  0.16130072, -0.17231926, -0.46056357, -0.39491645,
         0.12729669,  0.33289027, -0.00406086, -0.23342705, -0.00918353,
        -0.17865849,  0.17127913],
       [ 0.04650801,  0.5259019 , -0.19091046,  0.42628425,  0.18100399,
        -0.39816952, -

In [39]:
w1.shape

(8, 12)

In [38]:
b1

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.], dtype=float32)

In [40]:
# Compile the Model

# compile the keras model
model.compile(loss='binary_crossentropy', optimizer='adam', metrics=['accuracy'])

In [47]:
X_train, X_test, y_train, y_test = train_test_split(X,y, test_size=0.2, random_state=42)

In [48]:
# Fit the keras Model

# fit the keras model on the dataset
model.fit(X_train, y_train, epochs=150, batch_size=10)

Epoch 1/150
62/62 [==============================] - 0s 5ms/step - loss: 0.5490 - accuracy: 0.7020
Epoch 2/150
62/62 [==============================] - 0s 5ms/step - loss: 0.5559 - accuracy: 0.6938
Epoch 3/150
62/62 [==============================] - 0s 5ms/step - loss: 0.5579 - accuracy: 0.7068
Epoch 4/150
62/62 [==============================] - 0s 5ms/step - loss: 0.5421 - accuracy: 0.7036
Epoch 5/150
62/62 [==============================] - 0s 5ms/step - loss: 0.5411 - accuracy: 0.7134
Epoch 6/150
62/62 [==============================] - 0s 5ms/step - loss: 0.5498 - accuracy: 0.7166
Epoch 7/150
62/62 [==============================] - 0s 5ms/step - loss: 0.5516 - accuracy: 0.6987
Epoch 8/150
62/62 [==============================] - 0s 5ms/step - loss: 0.5433 - accuracy: 0.7117
Epoch 9/150
62/62 [==============================] - 0s 5ms/step - loss: 0.5490 - accuracy: 0.7068
Epoch 10/150
62/62 [==============================] - 0s 5ms/step - loss: 0.5418 - accuracy: 0.7068
Epoch 11/

In [49]:

# evaluate the keras model
_, accuracy = model.evaluate(X_test, y_test)
print('Accuracy: %.2f' % (accuracy*100))

5/5 [==============================] - 0s 3ms/step - loss: 0.7030 - accuracy: 0.6753


Accuracy: 67.53


In [54]:
# make class predictions with the model


predictions = (model.predict(X_test) > 0.5).astype(int)

5/5 [==============================] - 0s 2ms/step


In [55]:
predictions[0]

array([1])

In [70]:
# summarize the first 5 cases
for i in range(20):
    print(f'predicted value {predictions[i]} and expected value {np.array(y_test)[i]}')

predicted value [1] and expected value 0
predicted value [0] and expected value 0
predicted value [0] and expected value 0
predicted value [0] and expected value 0
predicted value [1] and expected value 0
predicted value [1] and expected value 0
predicted value [0] and expected value 0
predicted value [0] and expected value 0
predicted value [1] and expected value 0
predicted value [1] and expected value 0
predicted value [1] and expected value 1
predicted value [1] and expected value 0
predicted value [0] and expected value 1
predicted value [0] and expected value 0
predicted value [0] and expected value 0
predicted value [1] and expected value 1
predicted value [0] and expected value 0
predicted value [0] and expected value 0
predicted value [0] and expected value 1
predicted value [0] and expected value 1
