In [1]:
import numpy as np
import pandas as pd
import tensorflow as tf
from tensorflow import keras
from tensorflow.keras.models import Sequential
from tensorflow.keras import layers

from sklearn.model_selection import train_test_split

2024-04-03 12:15:41.067525: E tensorflow/compiler/xla/stream_executor/cuda/cuda_dnn.cc:9342] Unable to register cuDNN factory: Attempting to register factory for plugin cuDNN when one has already been registered
2024-04-03 12:15:41.067565: E tensorflow/compiler/xla/stream_executor/cuda/cuda_fft.cc:609] Unable to register cuFFT factory: Attempting to register factory for plugin cuFFT when one has already been registered
2024-04-03 12:15:41.067599: E tensorflow/compiler/xla/stream_executor/cuda/cuda_blas.cc:1518] Unable to register cuBLAS factory: Attempting to register factory for plugin cuBLAS when one has already been registered
2024-04-03 12:15:41.080526: I tensorflow/core/platform/cpu_feature_guard.cc:182] This TensorFlow binary is optimized to use available CPU instructions in performance-critical operations.
To enable the following instructions: AVX2 AVX512F FMA, in other operations, rebuild TensorFlow with the appropriate compiler flags.


In [2]:
# load the dataset

df = pd.read_csv('diabetes.csv', delimiter=',')
df.head()

times_pragnent  glucose_concentration  blood_pressure  skin_thickness  \
0               6                    148              72              35   
1               1                     85              66              29   
2               8                    183              64               0   
3               1                     89              66              23   
4               0                    137              40              35   

   insulin_serum   bmi    dpf  age  class  
0              0  33.6  0.627   50      1  
1              0  26.6  0.351   31      0  
2              0  23.3  0.672   32      1  
3             94  28.1  0.167   21      0  
4            168  43.1  2.288   33      1

In [3]:
df.shape

(768, 9)

In [4]:
# split into input (X) and output (y) variables
X = df.iloc[:,0:8]
y = df.iloc[:,8]


In [5]:
X

times_pragnent  glucose_concentration  blood_pressure  skin_thickness  \
0                 6                    148              72              35   
1                 1                     85              66              29   
2                 8                    183              64               0   
3                 1                     89              66              23   
4                 0                    137              40              35   
..              ...                    ...             ...             ...   
763              10                    101              76              48   
764               2                    122              70              27   
765               5                    121              72              23   
766               1                    126              60               0   
767               1                     93              70              31   

     insulin_serum   bmi    dpf  age  
0                0  33.6  0.627   50  
1                0  26.6  0.351   31  
2                0  23.3  0.672   32  
3               94  28.1  0.167   21  
4              168  43.1  2.288   33  
..             ...   ...    ...  ...  
763            180  32.9  0.171   63  
764              0  36.8  0.340   27  
765            112  26.2  0.245   30  
766              0  30.1  0.349   47  
767              0  30.4  0.315   23  

[768 rows x 8 columns]

In [6]:
# Define the Tensorflow Model
model = Sequential()

# adding layers

model.add(layers.Dense(12, input_shape=(8,), activation = 'relu'))

model.add(layers.Dense(8, activation='relu'))

model.add(layers.Dense(1, activation='sigmoid'))

2024-04-03 12:15:43.935872: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1886] Created device /job:localhost/replica:0/task:0/device:GPU:0 with 7395 MB memory:  -> device: 0, name: Quadro P4000, pci bus id: 0000:3b:00.0, compute capability: 6.1


In [7]:
model.summary()

Model: "sequential"
_________________________________________________________________
 Layer (type)                Output Shape              Param #   
 dense (Dense)               (None, 12)                108       
                                                                 
 dense_1 (Dense)             (None, 8)                 104       
                                                                 
 dense_2 (Dense)             (None, 1)                 9         
                                                                 
Total params: 221 (884.00 Byte)
Trainable params: 221 (884.00 Byte)
Non-trainable params: 0 (0.00 Byte)
_________________________________________________________________


In [8]:
w1,b1 = model.layers[0].get_weights()
w1

array([[-0.50054115,  0.13770556,  0.18740559,  0.49298084, -0.18887302,
         0.3284012 , -0.30559844,  0.19794124, -0.53164726,  0.44567907,
        -0.2635586 ,  0.26800734],
       [-0.15030971, -0.13028324,  0.41797203,  0.2809654 ,  0.1445474 ,
        -0.20810682,  0.21631098,  0.36416483, -0.00564516,  0.34921235,
         0.34071332, -0.09528312],
       [ 0.23814017, -0.42429584, -0.40772143,  0.14062417,  0.20801657,
        -0.293657  ,  0.31960297,  0.5427753 ,  0.03933966,  0.14253503,
         0.45189518,  0.26501703],
       [ 0.11429024, -0.11314693,  0.51154196, -0.11277422, -0.04405999,
         0.13094032, -0.19522128,  0.5050633 , -0.30090004,  0.19045037,
         0.2227279 ,  0.44332957],
       [ 0.541661  , -0.1055986 ,  0.3118137 ,  0.190629  ,  0.06688315,
         0.48017251, -0.28614458, -0.04744196,  0.31876516,  0.1497615 ,
         0.34428096,  0.5198153 ],
       [ 0.21062964,  0.30111825, -0.01086932,  0.5452198 , -0.0235582 ,
        -0.53779274, -

In [9]:
w1.shape

(8, 12)

In [10]:
b1

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.], dtype=float32)

In [11]:
b1.shape

(12,)

In [12]:
# Compile the Model

# compile the keras model
model.compile(loss='binary_crossentropy', optimizer='adam', metrics=['accuracy'])

In [13]:
X_train, X_test, y_train, y_test = train_test_split(X,y, test_size=0.2, random_state=42)

In [14]:
# Fit the keras Model

# fit the keras model on the dataset
model.fit(X_train, y_train, epochs=150, batch_size=10)

Epoch 1/150


2024-04-03 12:15:45.979588: I tensorflow/compiler/xla/service/service.cc:168] XLA service 0x7f4e9009bb80 initialized for platform CUDA (this does not guarantee that XLA will be used). Devices:
2024-04-03 12:15:45.979619: I tensorflow/compiler/xla/service/service.cc:176]   StreamExecutor device (0): Quadro P4000, Compute Capability 6.1
2024-04-03 12:15:45.984937: I tensorflow/compiler/mlir/tensorflow/utils/dump_mlir_util.cc:269] disabling MLIR crash reproducer, set env var `MLIR_CRASH_REPRODUCER_DIRECTORY` to enable.
2024-04-03 12:15:46.191972: I tensorflow/compiler/xla/stream_executor/cuda/cuda_dnn.cc:442] Loaded cuDNN version 8700
2024-04-03 12:15:46.320227: I ./tensorflow/compiler/jit/device_compiler.h:186] Compiled cluster using XLA!  This line is logged at most once for the lifetime of the process.


62/62 [==============================] - 3s 5ms/step - loss: 13.3063 - accuracy: 0.4218
Epoch 2/150
62/62 [==============================] - 0s 5ms/step - loss: 3.0476 - accuracy: 0.5782
Epoch 3/150
62/62 [==============================] - 0s 5ms/step - loss: 1.2081 - accuracy: 0.5619
Epoch 4/150
62/62 [==============================] - 0s 5ms/step - loss: 1.0207 - accuracy: 0.5603
Epoch 5/150
62/62 [==============================] - 0s 5ms/step - loss: 0.9602 - accuracy: 0.5440
Epoch 6/150
62/62 [==============================] - 0s 5ms/step - loss: 0.8657 - accuracy: 0.5586
Epoch 7/150
62/62 [==============================] - 0s 5ms/step - loss: 0.8163 - accuracy: 0.5668
Epoch 8/150
62/62 [==============================] - 0s 5ms/step - loss: 0.7964 - accuracy: 0.5749
Epoch 9/150
62/62 [==============================] - 0s 5ms/step - loss: 0.7507 - accuracy: 0.6026
Epoch 10/150
62/62 [==============================] - 0s 5ms/step - loss: 0.7097 - accuracy: 0.6156
Epoch 11/150
62/62 [

In [15]:

# evaluate the keras model

_, accuracy = model.evaluate(X_test, y_test)
print('Accuracy: %.2f' % (accuracy*100))

5/5 [==============================] - 0s 3ms/step - loss: 0.5313 - accuracy: 0.7792
Accuracy: 77.92


In [16]:
# make class predictions with the model


predictions = (model.predict(X_test) > 0.5).astype(int)

5/5 [==============================] - 0s 2ms/step


In [17]:
predictions

array([[1],
       [0],
       [0],
       [0],
       [0],
       [1],
       [0],
       [0],
       [1],
       [0],
       [0],
       [1],
       [1],
       [0],
       [0],
       [1],
       [0],
       [0],
       [1],
       [0],
       [0],
       [0],
       [0],
       [0],
       [1],
       [1],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [1],
       [1],
       [0],
       [1],
       [1],
       [0],
       [0],
       [1],
       [0],
       [0],
       [0],
       [0],
       [0],
       [1],
       [1],
       [0],
       [0],
       [1],
       [0],
       [1],
       [1],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [1],
       [1],
       [0],
       [1],
       [1],
       [0],
       [0],
       [0],
       [0],
       [0],
       [1],
       [1],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [1],
       [0],
       [0],
    

In [18]:
# summarize the first 5 cases
for i in range(20):
    print(f'predicted value {predictions[i]} and expected value {np.array(y_test)[i]}')

predicted value [1] and expected value 0
predicted value [0] and expected value 0
predicted value [0] and expected value 0
predicted value [0] and expected value 0
predicted value [0] and expected value 0
predicted value [1] and expected value 0
predicted value [0] and expected value 0
predicted value [0] and expected value 0
predicted value [1] and expected value 0
predicted value [0] and expected value 0
predicted value [0] and expected value 1
predicted value [1] and expected value 0
predicted value [1] and expected value 1
predicted value [0] and expected value 0
predicted value [0] and expected value 0
predicted value [1] and expected value 1
predicted value [0] and expected value 0
predicted value [0] and expected value 0
predicted value [1] and expected value 1
predicted value [0] and expected value 1


In [19]:
model.save('model_1.pickle')

INFO:tensorflow:Assets written to: model_1.pickle/assets


INFO:tensorflow:Assets written to: model_1.pickle/assets
